# Generated by Django 3.2.4 on 2021-06-30 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('panid', models.CharField(max_length=50)),
                ('request_date', models.DateField(default=datetime.datetime(2021, 6, 30, 1, 56, 4, 321921, tzinfo=utc))),
            ],
        ),
    ]
