# Generated by Django 3.2.4 on 2021-06-30 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_info',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request_info',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 6, 26, 52, 175486, tzinfo=utc)),
        ),
    ]
